package com.intecon.docsign.model;

public class DocumentModel {
	
	private String documentId; // MongoDb AutoGenerated ID 
	private byte[] binaryData; // Binary data of the file
	private String fileExtension; 
	private String key;
	private String client; // signature client name
	private boolean signed; // signature flag
	private String crt_date; // Document creation date
	private String sign_date; // Signature date
	private String erpID; // Client ERP ID
	private String documentUrl; // Local URL of the document. Can be different in LN, Server and Local Device
	private String name; // Name of the document( extension excluded ) 
	private String trid; // Unique transaction id
	private String bytesData; // Encoded String version of binary data of the file
	private String status; // status of the file
	
	public String getBytesData() {
		return bytesData;
	}
	public void setBytesData(String bytesData) {
		this.bytesData = bytesData;
	}
	public String getDocumentUrl() {
		return documentUrl;
	}
	public void setDocumentUrl(String documentUrl) {
		this.documentUrl = documentUrl;
	}
	public byte[] getBinaryData() {
		return binaryData;
	}
	public void setBinaryData(byte[] binaryData) {
		this.binaryData = binaryData;
	}
	public String getFileExtension() {
		return fileExtension;
	}
	public void setFileExtension(String fileExtension) {
		this.fileExtension = fileExtension;
	}
	public String getErpID() {
		return erpID;
	}
	public void setErpID(String erpID) {
		this.erpID = erpID;
	}
	public String getKey() {
		return key;
	}
	public void setKey(String key) {
		this.key = key;
	}
	
	public String getClient() {
		return client;
	}
	public void setClient(String client) {
		this.client = client;
	}
	public String getDocumentId() {
		return documentId;
	}

	public boolean isSigned() {
		return signed;
	}
	public void setSigned(boolean signed) {
		this.signed = signed;
	}
	public String getCrt_date() {
		return crt_date;
	}
	public void setCrt_date(String crt_date) {
		this.crt_date = crt_date;
	}
	public void setDocumentId(String documentId) {
		this.documentId = documentId;
	}
	@Override
	public String toString() {
		return "DocumentModel [binaryData=" + binaryData + ", fileExtansion=" + fileExtension + ", key=" + key
				+ ", client=" + client + "]";
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getTrid() {
		return trid;
	}
	public void setTrid(String trid) {
		this.trid = trid;
	}
	public String getSign_date() {
		return sign_date;
	}
	public void setSign_date(String sign_date) {
		this.sign_date = sign_date;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
}
